services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=false
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./db/data:/data
      - ./db/logs:/logs
      - ./db/import:/var/lib/neo4j/import
      - ./db/plugins:/plugins